[package]
name = "fuwa_ark_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
rcon = {version="0.6.0", features = ["rt-async-std"]}
serenity = "0.11.5"
tokio = { version="1.23.0", features = ["full"] }


